// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
var SquareVerifier = artifacts.require('Verifier');
var JsonProof = require('../../zokrates/code/square/proof.json');

contract('TestSquareVerifier', accounts => {
    // Test verification with correct proof
    // - use the contents from proof.json generated from zokrates steps

    describe('Verify Zokrate proof', function () {
        beforeEach(async function () { 
            this.contract = await SquareVerifier.new({from: accounts[0]});
        })

        it('Test verification with correct proof', async function () { 

            let tx = await this.contract.verifyTx(
                JsonProof.proof["a"],
                JsonProof.proof["b"],
                JsonProof.proof["c"], 
                JsonProof.input
            );

            assert.equal(tx, true, "Test fail. Incorrect inputs."); 
        });

        it('Test verification with incorrect proof', async function () { 

            let tx = await this.contract.verifyTx(
                JsonProof.proof["a"],
                JsonProof.proof["b"],
                JsonProof.proof["c"], 
                [3,4]
            );

            assert.equal(tx, false, "Test fail! Correct inputs."); 
        });

    });

})

    
// Test verification with incorrect proof
